apiVersion: apps/v1
kind: Deployment
metadata:
  name: complete-prodcution-e2e-pipeline-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      run: complete-prodcution-e2e-app
  template:
    metadata:
      labels:
        run: complete-prodcution-e2e-app
    spec:
      containers:
      - name: complete-prodcution-e2e-app
        image: eduardopessin/complete-prodcution-e2e-pipeline:1.0.0-38
        ports:
          - containerPort: 8080
        
